//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerbosIrregulares
{
    using System;
    using System.Collections.Generic;
    
    public partial class Verb
    {
        public int id { get; set; }
        public string baseForm { get; set; }
        public string pastSimple { get; set; }
        public string pastParticiple { get; set; }
        public string translate { get; set; }
        public Nullable<int> priority { get; set; }
    }
}
